version: "3.9"

services:
  riven-db:
    image: postgres:17-alpine
    container_name: riven-db
    restart: unless-stopped
    env_file: [.env]
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - riven-pg-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  riven:
    image: spoked/riven:dev
    container_name: riven
    restart: unless-stopped
    shm_size: 1024m
    ports:
      - "8080:8080"
    tty: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    env_file: [.env]
    environment:
      TZ: ${TZ}
      PUID: 1000
      PGID: 1000
      RIVEN_FORCE_ENV: "true"
      RIVEN_API_KEY: ${BACKEND_API_KEY}
      RIVEN_DATABASE_HOST: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@riven-db:5432/${POSTGRES_DB}
      RIVEN_FILESYSTEM_MOUNT_PATH: /mount
      RIVEN_UPDATERS_LIBRARY_PATH: /mnt/riven
      RIVEN_FILESYSTEM_CACHE_DIR: /dev/shm/riven-cache
    volumes:
      - /mnt/riven/backend:/riven/data
      - /mnt/riven/mount:/mount:rshared,z
    depends_on:
      riven-db:
        condition: service_healthy
    healthcheck:
      test: curl -s http://localhost:8080 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 10

  riven-frontend:
    image: spoked/riven-frontend:dev
    container_name: riven-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: [.env]
    environment:
      TZ: ${TZ}
      DATABASE_URL: /riven/data/riven.db
      BACKEND_URL: http://riven:8080
      BACKEND_API_KEY: ${BACKEND_API_KEY}
      AUTH_SECRET: ${AUTH_SECRET}
      ORIGIN: http://localhost:3000
    volumes:
      - riven-frontend-data:/riven/data
    depends_on:
      riven:
        condition: service_healthy

volumes:
  riven-frontend-data:
  riven-pg-data:
